---
title: "Update Me"
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = paste0(substr(inputFile,1,nchar(inputFile)-4),format(Sys.time(), "_%Y-%m-%d_%H:%M"),'.html')) })
output:
  html_document: default
  pdf_document: default
---

```{r, include=FALSE}
#Note this notebook expects to use the raw output sav file from the Import_final.Rmd notebook

#TODO: Follow the TODOs below

library(sjPlot)
library(tidyverse)
library(Hmisc)
library(weights)
library(descr)
library(car)
library(anesrake)
library(openxlsx)
library(sjlabelled) #Adding this library to more easily access labels from dataframe columns
library(haven)
library(htmlTable)
library(comprehenr) #For Python like list comprehension
library(wordcloud)
library(tm)
library(scales)
#this needs to come after tidyverse, b/c needs to be loaded after haven
library(expss)
library(rlist)
library(ggplot2)
library(GGally)
library(gridExtra)
library(extrafont)
library(quanteda)
library(quanteda.textplots)
library(quanteda.textstats)
library(quanteda.textmodels)
```

```{r, results="asis",echo=FALSE,include=FALSE}
cat(paste("This file was generated at: "))
st=format(Sys.time(), "%Y-%m-%d_%H:%M")
cat(paste(st))
```

```{r, include=FALSE}
#TODO Update file path to raw sav file, this is the file that contains the data with weights and audiences already applied

#Reading in the data
file_name = "raw_poll_post_weighting_test.sav"
raw_poll=haven::read_spss(file_name)

#TODO update questions to look at
emotion_qs = c("Q38","Q40")

#Add labelled class and rename audience to df
expss_digits(digits = 0) #Round digits
df = raw_poll

```

```{r, audience Category,echo=FALSE,results="asis"}
#TODO update name of audience variable below
audience_category = "RI_Audience_categories"
cat(paste("<h5>",audience_category,"</h5>"))
```


```{r final plots, echo=FALSE,results="asis", warning=FALSE}
#This is for regular emotion plots

#Title wrapper function to work with ggplot titles that need \n inserted to wrap
#ggplot does not autowrap text and we need to insert newlines
wrapper <- function(x, ...) 
{
  paste(strwrap(x, ...), collapse = "\n")
}

#colors to set for each audience
colors = c("Base" = "#54a545", "Opposition" = "#e46c64", "Persuadable" = "#5c8cf3")


for (q in emotion_qs){
  
  #Need to work with labels not values so can set as factors and filter out NAs
  temp = df %>%
    #convert to factor to filter out nas without losing the labels
    mutate_all(as_factor) %>%
    filter(!is.na(df[[q]]))

  #Need to reset weights back to numeric after the mutate all to factor conversion above
  temp$weightcompressed = as.numeric(temp$weightcompressed)

  
  #Start the plotting code
  plot = ggplot(data=temp) +
  
    #use stat prop for percent of audience
    #set by to let stat prop know what to consider 100%
    #fill is fill color while color is border
    aes(y=temp[[q]], fill=temp[[audience_category]], weight=temp$weightcompressed, by=temp[[audience_category]], x=after_stat(prop)) +
  
    #Dodging preserves the vertical position of an geom while adjusting the horizontal position
    geom_bar(stat="prop", position="dodge") +
  
    #facet grid separates the audiences in the x
    facet_grid(~temp[[audience_category]]) +
    labs(
      #Just need to get the full message for the title so okay if send df
      title = wrapper(var_lab(df[[q]]), width = 78),
      y= 'After reading this message, which of the\nfollowing best describes your feelings?',
      x = "Percent of Audience Group", family="Open Sans") +
    
    #Specify text size/position
    theme(axis.text.y = element_text(angle = 0,hjust=1,size=12), plot.title=element_text(size=11), axis.ticks.x = element_blank(), axis.text.x = element_blank(), legend.position = "none") +
  scale_x_continuous(labels = scales::percent) +
  
  #geom text is for the % text on the bars
  geom_text(
    mapping = aes(
      #show the % of the prop stat
      label = scales::percent(after_stat(prop), accuracy = 1)
    ),
    #vjust = 1,
    position = position_stack(0.5),
    stat = "prop", size=3
  )+
  #Set the colors to the ones I defined above
  scale_fill_manual(values = colors)


#plot.new() #Using this to create empty space after a plot since printing new lines doesn't seem to work
cat(paste("<h3>",strsplit(var_lab(df[[q]])," E - Selected Choice")[[1]],"</h3>"))
grid.arrange(plot,newpage = TRUE)
#ggsave(paste(audience_category,"_",q,".png",sep=""))

#Printing out Other (open ended) emotion text as strings after printing plots

# cat("<br><br>")
# cat("Base Respondents who selected Other wrote in:")
# cat("<br>")
# cat(df[[paste(q,"_9_TEXT",sep="")]][!is.na(df[[paste(q, "_9_TEXT", sep="")]]) & (df[[audience_category]]=="Base")], sep=" ; ")
# cat("<br><br>")
# cat("Persuadable Respondents who selected Other wrote in:")
# cat("<br>")
# cat(df[[paste(q, "_9_TEXT", sep="")]][!is.na(df[[paste(q, "_9_TEXT", sep="")]]) & (df[[audience_category]]=="Persuadable")],sep=" ; ")
# cat("<br><br>")
# cat("Opposition Respondents who selected Other wrote in:")
# cat("<br>")
# cat(df[[paste(q,"_9_TEXT",sep="")]][!is.na(df[[paste(q,"_9_TEXT",sep="")]])&(df[[audience_category]]=="Opposition")],sep=" ; ")
# cat("<br><br><br><br><br>")
}

```

```{r final plots with collapsed categories, echo=FALSE,results="asis", warning=FALSE}
#This is for emotion plots that collapse Inspired/Motivated to one category and Hopeless/Overwhelmed to another

wrapper <- function(x, ...) 
{
  paste(strwrap(x, ...), collapse = "\n")
}

#colors
colors = c("Base" = "#54a545", "Opposition" = "#e46c64", "Persuadable" = "#5c8cf3")

for (q in emotion_qs){
  
   #Need to work with labels not values so can set as factors and filter out NAs
  temp = df %>% 
    mutate_all(as_factor) %>%
    filter(!is.na(df[[q]]))
  
  temp[[q]] = recode_factor(temp[[q]], Inspired = "Inspired/Motivated", Motivated = "Inspired/Motivated", Hopeless = "Hopeless/Overwhelmed", Overwhelmed = "Hopeless/Overwhelmed")

  #Reorder emotions
temp[[q]] = factor(temp[[q]], levels = c("Angry","Hopeless/Overwhelmed","Skeptical","Worried","Other","Confident","Hopeful","Inspired/Motivated"))
  
  #Need to reset weights back to numeric after the mutate all to factor conversion above
  temp$weightcompressed = as.numeric(temp$weightcompressed)


plot = ggplot(data=temp) +
  #use stat prop for percent
  #set by to let stat prop know what to consider 100%
  #fill is fill color while color is border
  aes(y=temp[[q]],fill=temp[[audience_category]],weight=temp$weightcompressed,by=temp[[audience_category]],x=after_stat(prop)) +
  geom_bar(stat="prop",position="dodge") +
  
  #facet grid separates the audiences in the x
  facet_grid(~temp[[audience_category]]) +
  labs(
    #Just need to get the full message for the title so okay if send df
    title = wrapper(var_lab(df[[q]]), width = 67),
    y= 'After reading this message, which of the\nfollowing best describes your feelings?',
    x = "Percent of Audience Group",
  family="Open Sans"
  ) + 
  theme(axis.text.y = element_text(angle = 0,hjust=1,size=12),plot.title=element_text(size=11),axis.ticks.x =element_blank(),axis.text.x =element_blank(),
        legend.position = "none") +
  scale_x_continuous(labels = scales::percent) +
  #geom text is for the % text on the bars
  geom_text(
    mapping = aes(
      #show the % of the prop stat
      label = scales::percent(after_stat(prop), accuracy = 1)
    ),
    #vjust = 1,
    position = position_stack(0.5),
    stat = "prop", size=3
  )+ 
  #Set the colors to the ones I defined above
  scale_fill_manual(values = colors)

#plot.new() #Using this to create empty space after a plot since printing new lines doesn't seem to work
cat(paste("<h3>",strsplit(var_lab(df[[q]])," E - Selected Choice")[[1]],"</h3>"))
grid.arrange(plot,newpage = TRUE)
#ggsave(paste(audience_category,"_",q,"_collapsed.png",sep=""))

#Printing out Other emotion text as strings after printing plots 

# cat("<br><br>")
# cat("Base Respondents who selected Other wrote in:")
# cat("<br>")
# cat(df[[paste(q,"_9_TEXT",sep="")]][!is.na(df[[paste(q, "_9_TEXT", sep="")]]) & (df[[audience_category]]=="Base")], sep=" ; ")
# cat("<br><br>")
# cat("Persuadable Respondents who selected Other wrote in:")
# cat("<br>")
# cat(df[[paste(q, "_9_TEXT", sep="")]][!is.na(df[[paste(q, "_9_TEXT", sep="")]]) & (df[[audience_category]]=="Persuadable")],sep=" ; ")
# cat("<br><br>")
# cat("Opposition Respondents who selected Other wrote in:")
# cat("<br>")
# cat(df[[paste(q,"_9_TEXT",sep="")]][!is.na(df[[paste(q,"_9_TEXT",sep="")]])&(df[[audience_category]]=="Opposition")],sep=" ; ")
# cat("<br><br><br><br><br>")
}

```
